# Generated by Django 5.2.8 on 2026-01-07 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
        ('finance', '0002_canteeninvoice_canteenpayment'),
        ('students', '0004_alter_student_parent_mobile_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteeninvoice',
            options={'ordering': ['student']},
        ),
        migrations.AlterUniqueTogether(
            name='canteeninvoice',
            unique_together={('student', 'session')},
        ),
        migrations.AddField(
            model_name='canteeninvoice',
            name='datecreation',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.RemoveField(
            model_name='canteeninvoice',
            name='term',
        ),
    ]
