# Generated by Django 5.2.8 on 2026-01-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='baccalaureate_booklet',
            field=models.FileField(blank=True, null=True, upload_to='students/baccalaureate/'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='students/birth_certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.FileField(blank=True, null=True, upload_to='students/nationality/'),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_2',
            field=models.ImageField(blank=True, null=True, upload_to='students/passports/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='students/passports/'),
        ),
    ]
