# Generated by Django 5.2.8 on 2026-01-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_baccalaureate_booklet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_mobile_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
