# Generated by Django 5.2.8 on 2026-01-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='coefficient',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
